package Vistas;

import Controladores.ControladorRegistro;
import java.awt.event.ActionListener;

public class VistaRegistro extends javax.swing.JFrame {

    public VistaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        lblRptContrasena = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        txtRptContrasena = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblMensajeUsuario = new javax.swing.JLabel();
        lblMensajeContrasena = new javax.swing.JLabel();
        lblMensajeRptContrasena = new javax.swing.JLabel();
        logoRegisto = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre de usuario:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblContrasena.setText("Contraseña:");
        getContentPane().add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblRptContrasena.setText("Repita contraseña:");
        getContentPane().add(lblRptContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        txtUsuario.setText("Nombre de usuario");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 125, -1));
        txtUsuario.getAccessibleContext().setAccessibleName("Usuario");

        txtContrasena.setText("jPasswordField1");
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 125, -1));

        txtRptContrasena.setText("jPasswordField2");
        getContentPane().add(txtRptContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 125, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setActionCommand("cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        btnRegistrar.setText("Registrarse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        lblMensajeUsuario.setForeground(new java.awt.Color(255, 0, 0));
        lblMensajeUsuario.setText("*");
        getContentPane().add(lblMensajeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        lblMensajeContrasena.setForeground(new java.awt.Color(255, 0, 0));
        lblMensajeContrasena.setText("*");
        getContentPane().add(lblMensajeContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        lblMensajeRptContrasena.setForeground(new java.awt.Color(255, 0, 0));
        lblMensajeRptContrasena.setText("*");
        getContentPane().add(lblMensajeRptContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        logoRegisto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/logoRegistro.png"))); // NOI18N
        getContentPane().add(logoRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondos/registro.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }
    public void setListener(ActionListener interaccion){
        btnCancelar.addActionListener(interaccion);
        btnRegistrar.addActionListener(interaccion);
    }
    public String getUsuario(){
        return txtUsuario.getText();
    }
    public String getContrasena(){
        return txtContrasena.getText();
    }
    public String getRptContrasena(){
        return txtRptContrasena.getText();        
    }
    public void setContrasena(String mensaje){
        txtContrasena.setText(mensaje);
    }
    public void setRptContrasena(String mensaje){
        txtRptContrasena.setText(mensaje);
    }
    public void setMensajeUsuario(String mensaje){
        lblMensajeUsuario.setText(mensaje);
    }
    public void setMensajeContrasena(String mensaje){
        lblMensajeContrasena.setText(mensaje);
    }
    public void setMensajeRptContrasena(String mensaje){
        lblMensajeRptContrasena.setText(mensaje);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblMensajeContrasena;
    private javax.swing.JLabel lblMensajeRptContrasena;
    private javax.swing.JLabel lblMensajeUsuario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRptContrasena;
    private javax.swing.JLabel logoRegisto;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JPasswordField txtRptContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
