package Vistas;

import java.awt.event.ActionListener;

public class VistaEntregarCriatura extends javax.swing.JFrame {

    public VistaEntregarCriatura() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        lblImg1 = new javax.swing.JLabel();
        lblCriatura1 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblCriatura2 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        lblCriatura3 = new javax.swing.JLabel();
        lblImg4 = new javax.swing.JLabel();
        lblCriatura4 = new javax.swing.JLabel();
        lblImg5 = new javax.swing.JLabel();
        lblCriatura5 = new javax.swing.JLabel();
        lblImg6 = new javax.swing.JLabel();
        lblCriatura6 = new javax.swing.JLabel();
        lblImg7 = new javax.swing.JLabel();
        lblCriatura7 = new javax.swing.JLabel();
        lblImg8 = new javax.swing.JLabel();
        lblCriatura8 = new javax.swing.JLabel();
        lblImg9 = new javax.swing.JLabel();
        lblCriatura9 = new javax.swing.JLabel();
        lblImg10 = new javax.swing.JLabel();
        lblCriatura10 = new javax.swing.JLabel();
        lblImg11 = new javax.swing.JLabel();
        lblCriatura11 = new javax.swing.JLabel();
        lblImg12 = new javax.swing.JLabel();
        lblCriatura12 = new javax.swing.JLabel();
        lblImg13 = new javax.swing.JLabel();
        lblCriatura13 = new javax.swing.JLabel();
        lblImg14 = new javax.swing.JLabel();
        lblCriatura14 = new javax.swing.JLabel();
        lblImg15 = new javax.swing.JLabel();
        lblCriatura15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSiguiente.setText("Siguiente");

        btnAnterior.setText("Anterior");

        lblImg1.setText("jLabel1");

        lblCriatura1.setText("jLabel2");

        lblImg2.setText("jLabel3");

        lblCriatura2.setText("jLabel4");

        lblImg3.setText("jLabel5");

        lblCriatura3.setText("jLabel6");

        lblImg4.setText("jLabel7");

        lblCriatura4.setText("jLabel8");

        lblImg5.setText("jLabel9");

        lblCriatura5.setText("jLabel10");

        lblImg6.setText("jLabel3");

        lblCriatura6.setText("jLabel2");

        lblImg7.setText("jLabel5");

        lblCriatura7.setText("jLabel4");

        lblImg8.setText("jLabel7");

        lblCriatura8.setText("jLabel6");

        lblImg9.setText("jLabel9");

        lblCriatura9.setText("jLabel8");

        lblImg10.setText("jLabel1");

        lblCriatura10.setText("jLabel10");

        lblImg11.setText("jLabel1");

        lblCriatura11.setText("jLabel10");

        lblImg12.setText("jLabel3");

        lblCriatura12.setText("jLabel2");

        lblImg13.setText("jLabel5");

        lblCriatura13.setText("jLabel4");

        lblImg14.setText("jLabel7");

        lblCriatura14.setText("jLabel6");

        lblImg15.setText("jLabel9");

        lblCriatura15.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 129, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCriatura6)
                                    .addComponent(lblImg6))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg7)
                                    .addComponent(lblCriatura7))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCriatura8)
                                    .addComponent(lblImg8))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCriatura9)
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCriatura10)
                                            .addComponent(lblImg10)))
                                    .addComponent(lblImg9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCriatura1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCriatura2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblImg1)
                                        .addGap(90, 90, 90)
                                        .addComponent(lblImg2)))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblImg3)
                                    .addComponent(lblCriatura3))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblImg4)
                                        .addGap(90, 90, 90)
                                        .addComponent(lblImg5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCriatura4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCriatura5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCriatura12)
                                    .addComponent(lblImg12))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg13)
                                    .addComponent(lblCriatura13))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCriatura14)
                                    .addComponent(lblImg14))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCriatura15)
                                        .addGap(84, 84, 84)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblCriatura11)
                                            .addComponent(lblImg11)))
                                    .addComponent(lblImg15))))
                        .addGap(131, 131, 131))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImg1)
                    .addComponent(lblImg2)
                    .addComponent(lblImg3)
                    .addComponent(lblImg4)
                    .addComponent(lblImg5))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriatura1)
                    .addComponent(lblCriatura2)
                    .addComponent(lblCriatura3)
                    .addComponent(lblCriatura4)
                    .addComponent(lblCriatura5))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImg6)
                    .addComponent(lblImg7)
                    .addComponent(lblImg8)
                    .addComponent(lblImg9)
                    .addComponent(lblImg10))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriatura6)
                    .addComponent(lblCriatura7)
                    .addComponent(lblCriatura8)
                    .addComponent(lblCriatura9)
                    .addComponent(lblCriatura10))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImg12)
                    .addComponent(lblImg13)
                    .addComponent(lblImg14)
                    .addComponent(lblImg15)
                    .addComponent(lblImg11))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCriatura12)
                    .addComponent(lblCriatura13)
                    .addComponent(lblCriatura14)
                    .addComponent(lblCriatura15)
                    .addComponent(lblCriatura11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEntregarCriatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEntregarCriatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEntregarCriatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEntregarCriatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEntregarCriatura().setVisible(true);
            }
        });
    }
    public void setListener(ActionListener presionar) {
    btnSiguiente.addActionListener(presionar);
    btnAnterior.addActionListener(presionar);       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblCriatura1;
    private javax.swing.JLabel lblCriatura10;
    private javax.swing.JLabel lblCriatura11;
    private javax.swing.JLabel lblCriatura12;
    private javax.swing.JLabel lblCriatura13;
    private javax.swing.JLabel lblCriatura14;
    private javax.swing.JLabel lblCriatura15;
    private javax.swing.JLabel lblCriatura2;
    private javax.swing.JLabel lblCriatura3;
    private javax.swing.JLabel lblCriatura4;
    private javax.swing.JLabel lblCriatura5;
    private javax.swing.JLabel lblCriatura6;
    private javax.swing.JLabel lblCriatura7;
    private javax.swing.JLabel lblCriatura8;
    private javax.swing.JLabel lblCriatura9;
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg10;
    private javax.swing.JLabel lblImg11;
    private javax.swing.JLabel lblImg12;
    private javax.swing.JLabel lblImg13;
    private javax.swing.JLabel lblImg14;
    private javax.swing.JLabel lblImg15;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JLabel lblImg5;
    private javax.swing.JLabel lblImg6;
    private javax.swing.JLabel lblImg7;
    private javax.swing.JLabel lblImg8;
    private javax.swing.JLabel lblImg9;
    // End of variables declaration//GEN-END:variables

}
